POST http://localhost:3000/schedule
Content-Type: application/json

{
 "client": {
  "id": "b3b6c8e2-1f2a-4c3a-9e7a-123456789abc",
  "name": "Maria Silva"
 },
 "startDate": "2025-07-15T09:00:00.000Z",
 "endDate": "2025-07-15T10:00:00.000Z"
}

###
GET http://localhost:3000/schedule/price/ccbc2836-a8eb-48fb-9b4d-6cc51aa4177b/b


###
GET http://localhost:3000/schedule