### Create client
POST http://localhost:3000/clients
Content-Type: application/json

{
 "name": "Vagner",
 "email": "juniorterriaga0@gmail.com",
 "phone": "11956542085",
 "rg": "540246827",
 "cpf": "47223888814",
 "active": true
}



### Create schedule
POST http://localhost:3000/schedules
Content-Type: application/json

{
 "client": {
  "id": "9952e905-e644-4bab-8bc1-d65466870b2a"
 },
 "startDate": "2025-07-16T09:00:00.000Z",
 "endDate": "2025-07-16T10:00:00.000Z",
 "billingType": "Common"
}

