services:

  appointment_db:
    image: postgres:15
    container_name: appointment_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - appointment_db_data:/var/lib/postgresql/data
    networks:
      - appointment_network

  redis:
    image: redis:7
    container_name: appointment_redis_service
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - appointment_network

networks:
  appointment_network:
    driver: bridge

volumes:
  appointment_db_data: